# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a8516d5102fbb344f1b55f7565cdda749beaa963d1ccbc1b972c4a146a1c8f31ca74d77cd45f714f53d4d09d07a340fb70ae727285e6bab532a54a59dd92d5f4

test:
  secret_key_base: 42cc3a05286cbe4b78d39297595b2559e07dcf8176e3414d4f733e1fb7b79b2e485bf440a38036d9b07c0b880fee4ee69e7baa0794c100a7b5b1bf98cac507a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
